### ISSUE TITLE
4.2 Roadmap

### ISSUE THREAD

**Issue by Dev-Owl** [Dev-Owl/pillowsharp#7]
- [ ] Update all dependencies before release to latest stable
- [ ] Support Text.Json for all build in models alongside Newtonsoft 
- [ ] Add support for Active tasks endpoint
- [ ] Upgrade all test to use Async methods and reduce warnings to minimum
